services:
  web:
    container_name: iot-server
    build: .
    volumes:
      - ./logs.txt:/logs.txt
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: iot-postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 50
  redis:
    container_name: iot-redis
    image: redis:latest
#    volumes:
#      - data:/data
    ports:
      - 6379:6379