
POST http://192.168.0.107:8080/code/send
Content-Type: application/json

{
  "email": ""
}

###
POST http://192.168.0.107:8080/code/verify
Content-Type: application/json

{
  "email": "",
  "code": ""
}

###
POST http://192.168.0.107:8080/account/register
Content-Type: application/json

{
  "number": "",
  "email": "",
  "password": ""
}

###
POST http://192.168.0.106:8080/account/login
Content-Type: application/json

{
  "email": "ziomki@yandex.ru",
  "password": "ilya123321"
}

###
POST http://192.168.0.103:8080/account/change/password
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###
GET http://192.168.0.106:8080/token/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNzo4MDgwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA3OjgwODAvIiwiaWQiOjEsInR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjc4NjE1NTY5fQ.WAd4wypjP4q43qqSR9LlfKPOV3tAQXZnCRikNUwBRrY

###
POST http://192.168.0.106:8080/management/user/sensors/change/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNjo4MDgwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA2OjgwODAvIiwiaWQiOjEsImV4cCI6MTY3NjgyMTc5NX0.OqaFS0KoSCxdrt-sApn13vefHaCjhxmqUID-zNuhdpU
Content-Type: application/json

{
  "sensor": "Мотор",
  "state": "false"
}

###
GET http://192.168.0.106:8080/management/user/devices/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNjo4MDgwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA2OjgwODAvIiwiaWQiOjEsInR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjc4ODk0Mjg2fQ.GumSW5S6qsAJOdBzZd46IWNRlbeuXcH2BkNv3QPMa0o