
POST http://192.168.0.107:8000/code/send
Content-Type: application/json

{
  "email": "sttich07@gmail.com"
}

###
POST http://192.168.0.107:8000/code/verify
Content-Type: application/json

{
  "email": "sttich07@gmail.com",
  "code": 853238
}

###
POST http://192.168.0.107:8000/account/register
Content-Type: application/json

{
  "email": "sttich07@gmail.com",
  "password": "ilya123321"
}

###
POST http://192.168.0.107:8000/account/login
Content-Type: application/json

{
  "email": "ziomki@yandex.ru",
  "password": "ilya123321"
}

###
POST http://192.168.0.103:8080/account/change/password
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###
GET http://192.168.0.107:8080/token/update
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNzo4MDgwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA3OjgwODAvIiwiaWQiOjEsInR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjc5MjQxODIxfQ.ZLo1-K9eTps7N1DAaj8XoPUPY4T5oLoKb9ICxbU_PxI

###
POST http://192.168.0.107:8000/management/user/devices/1/change
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNzo4MDAwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA3OjgwMDAvIiwiaWQiOjEsInR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjgwNjI1OTY3fQ.BEIUX2Ywea4UP5Kod7o60Hzmp0GeQHEJbTDACb8MQKo
Content-Type: application/json

{
  "sensor": "Мотор вверх",
  "state": "false"
}

###
GET http://192.168.0.107:8080/management/user/devices
Authorization: Bearer

###
GET http://192.168.0.107:8000/management/user/devices/3/reset
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMTkyLjE2OC4wLjEwNzo4MDAwLyIsImlzcyI6Imh0dHA6Ly8xOTIuMTY4LjAuMTA3OjgwMDAvIiwiaWQiOjEsInR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjgwNjI1OTY3fQ.BEIUX2Ywea4UP5Kod7o60Hzmp0GeQHEJbTDACb8MQKo