package com.iotserv.utils

object RoutesResponses {
    const val userAlreadyExists = "User already exists"
    const val userNotFound = "User not found"
    const val authorizationHasBeenCompleted = "Authorization has been completed"
    const val verifyCodeWasSent = "Verify code was sent"
    const val dataHasBeenAccepted = "Data has been accepted"
    const val userHasNotBeenAdded = "The user has not been added"
    const val userNotFoundOrPasswordIsIncorrect = "Such user not found or password is incorrect"
    const val exceptionEmailMessageSending = "Email was not sent"
    const val userIdWasNotFound = "User id was not found"
    const val authorizationError = "Authorization error"
    const val connectionTimeWasUp = "Connection time was up"
    const val sendingEmailException = "Sending email exception"
    const val codeIsRight = "Code is right"
    const val codeIsWrong = "Code is wrong"
    const val codeIsWrongOrNotVerified = "Code is wrong or not verified"
    const val passwordWasSuccessfullyChanged = "Password was successfully changed"
    const val dataWasSuccessfullyChanged = "Data was successfully changed"
    const val incorrectNumberLength = "Incorrect number length"
    const val incorrectNumberFormat = "Incorrect number format"
    const val incorrectEmailFormat = "Incorrect email format"
    const val incorrectEmailLength = "Incorrect email length"
    const val incorrectPasswordLength = "Incorrect password length"
    const val incorrectCodeLength = "Incorrect code length"
    const val incorrectCodeFormat = "Incorrect code format"
    const val suchSocketAlreadyExists = "Such socket already in"
    const val successfullyConnection = "Successfully connection"
    const val noConnection = "No connection"
    const val sendingSettingsAccepted = "Sending settings accepted"
    const val settingsSuccessfullyReceived = "Settings successfully received"
    const val unknownSocketCommand = "Unknown socket command"
    const val boardWasFound = "Board was found"
    const val boardWasNotFound = "Board was not found"
    const val userIdIsNotFound = "User id is not found"
    const val deviceHasNotBeenAdded = "Device has not been added"
    const val suchDeviceIdAlreadyRegistered = "Such device id already registered"
    const val deviceIdWasNotFound = "Device id was not found"
    const val integrityObjectsViolation = "Integrity objects violation"
    const val DataWereSuccessfullyWrote = "DataWereSuccessfullyWrote"
    const val deviceHasNotBeenAddedToUserBase = "Device has not been added to user base"
}